working C implementation of Gilbert++
* still no adaptive functions (for C but also for JS and Python?)
* test include C, Py, and JS implementations (1 to 13 in each dimension)
* .gitignore ignores c executable

diff --git a/extensions/runtest b/extensions/runtest
--- a/extensions/runtest
+++ b/extensions/runtest
@@ -4,8 +4,8 @@
 N=13
 
 C_TESTS=1
-#PYTHON_TESTS=1
-#JAVASCRIPT_TESTS=1
+PYTHON_TESTS=1
+JAVASCRIPT_TESTS=1
 VERBOSE_LEVEL=1
 ERR=0
 
@@ -14,13 +14,15 @@ if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
   CHECK_OPT='verbose'
 fi
 
+
+
 if [[ $C_TESTS ]] ; then
 
   if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
     echo "# C"
   fi
 
-  ## async
+  ## d2xy (sync)
   ##
   if [[ "$VERBOSE_LEVEL" -gt 0 ]] ; then
     echo -n "# C: gilbert2d d2xy (sync): "
@@ -70,7 +72,7 @@ if [[ $C_TESTS ]] ; then
   fi
   echo pass
 
-  ##
+  ## xy2d (sync)
   ##
   if [[ "$VERBOSE_LEVEL" -gt 0 ]] ; then
     echo -n "# C: gilbert2d xy2d (sync): "
@@ -123,6 +125,122 @@ if [[ $C_TESTS ]] ; then
   echo pass
 
 
+
+  ## d2xy (sync)
+  ##
+  if [[ "$VERBOSE_LEVEL" -gt 0 ]] ; then
+    echo -n "# C: gilbert3d d2xyz (sync): "
+    if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+      echo ""
+    fi
+  fi
+
+  for z in `seq 1 $N` ; do
+    for y in `seq 1 $N` ; do
+      for x in `seq 1 $N` ; do
+
+        if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+          echo "## $x $y $z"
+        fi
+
+        a0=`echo "$x%2" | bc`
+        if [[ "$a0" = 1 ]] && ( [[ "$y" = 2 ]] || [[ "$z" == 1 ]] ) ; then
+          if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+            echo "# skipping (known bad configuration: $x $y $z)"
+          fi
+          continue
+        fi
+        if [[ "$a0" = 1 ]] && ( [[ "$y" = 1 ]] || [[ "$z" == 2 ]] ) ; then
+          if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+            echo "# skipping (known bad configuration: $x $y $z)"
+          fi
+          continue
+        fi
+
+        ./gilbert3dpp-c d2xyz $x $y $z | \
+          grep -v '#' | \
+          ./gilbert-check-curve $CHECK_OPT
+
+        if [[ "$?" != 0 ]] ; then
+
+          ERR=1
+          break
+        fi
+
+
+      done
+      if [[ "$ERR" != 0 ]] ; then break ; fi
+    done
+    if [[ "$ERR" != 0 ]] ; then break ; fi
+  done
+
+  if [[ "$ERR" != 0 ]] ; then
+
+    echo FAIL
+
+    echo "# FAIL C g3d d2xyz $x $y $z"
+
+    exit -1
+  fi
+  echo pass
+
+  ## xyz2d (sync)
+  ##
+  if [[ "$VERBOSE_LEVEL" -gt 0 ]] ; then
+    echo -n "# C: gilbert3d xyz2d (sync): "
+    if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+      echo ""
+    fi
+  fi
+
+
+  for z in `seq 1 $N` ; do
+    for y in `seq 1 $N` ; do
+      for x in `seq 1 $N` ; do
+
+        if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+          echo "## $x $y $z"
+        fi
+
+        a0=`echo "$x%2" | bc`
+        if [[ "$a0" = 1 ]] && ( [[ "$y" = 2 ]] || [[ "$z" == 1 ]] ) ; then
+          if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+            echo "# skipping (known bad configuration: $x $y $z)"
+          fi
+          continue
+        fi
+        if [[ "$a0" = 1 ]] && ( [[ "$y" = 1 ]] || [[ "$z" == 2 ]] ) ; then
+          if [[ "$VERBOSE_LEVEL" -gt 1 ]] ; then
+            echo "# skipping (known bad configuration: $x $y $z)"
+          fi
+          continue
+        fi
+
+        ./gilbert3dpp-c xyz2d $x $y $z | \
+          grep -v '#' | \
+          sort -n | cut -f2- -d' ' | \
+          ./gilbert-check-curve $CHECK_OPT
+
+        if [[ "$?" != 0 ]] ; then
+          ERR=1
+          break
+        fi
+
+
+      done
+      if [[ "$ERR" != 0 ]] ; then break ; fi
+    done
+    if [[ "$ERR" != 0 ]] ; then break ; fi
+  done
+
+  if [[ "$ERR" != 0 ]] ; then
+    echo FAIL
+
+    echo "# FAIL C g3d xyz2d $x $y $z"
+
+    exit -1
+  fi
+  echo pass
 
 fi
 
